config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  resources :books
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :libraries
    has_many :students, through: :libraries
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :student
  belongs_to :book
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :libraries, dependent: :destroy
    has_many :books, through: :libraries
    validates :name, presence: true
    validates :age, numericality: { greater_than_or_equal_to: 14, less_than_or_equal_to: 18 }
    validates :grade, numericality: { greater_than_or_equal_to: 9, less_than_or_equal_to: 12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

    def new
        @library = Library.new
        @students = Student.all 
        @books = Book.all 
    end

    def create
        @library = Library.create(params.require(:library).permit(:student_id, :book_id))
        redirect_to student_path(@library.student_id)
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :find_student, except: [:index, :new, :create]

    def index
        @students = Student.all
    end

    def show
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)
        if @student.valid?
            redirect_to student_path(@student)
        else
          flash[:errors] = @student.errors.full_messages
          redirect_to new_student_path  
        end
    end

    def edit
    end

    def update
        if @student.update(student_params)
            redirect_to student_path(@student)
        else
            flash[:errors] = @student.errors.full_messages
            redirect_to edit_student_path(@student)
        end
    end

    def destroy
        @student.destroy
        redirect_to students_path
    end

    private

    def student_params
        params.require(:student).permit(:name, :age, :grade)
    end

    def find_student
        @student = Student.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/books/index.html.erb
<h1>Book Catalog</h1>
<hr>
<ul>
    <% @books.each do |book| %>
    <li><p><%= link_to book.title, book_path(book) %></p></li>
    <% end %>
</ul>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<hr>
<p><b>Author: </b> <%= @book.author %></p>
<br>
<p><b>Genre: </b> <%= @book.genre %></p>
<br>
<b>Summary: </b><br>
<br>
<%= @book.summary %>
<br>
<br>
<br>
<p><%= link_to "Index", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryPracticeCodeChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/new.html.erb
<h1>Library Book Checkout</h1>
<%= form_for @library do |f| %>
<br>
<br>
<label><b>Student:</b></label>
<%= f.collection_select :student_id,  @students, :id, :name %>
<br>
<br>
<label><b>Book:</b></label>
<%= f.collection_select :book_id,  @books, :id, :title %>
<br>
<br>
<%= f.submit "Checkout Book" %>
<% end %>

app/views/students/_form.html.erb
<% if flash[:errors] %>
<ul>
    <% flash[:errors].each do |error| %>
        <li><%= error %></li>
    <% end %>
</ul>
<% end %>
<br>
<h1>Student Form</h1>
<br>
<%= form_for @student do |f| %>
<label><b>Name: </b></label>
<%= f.text_field :name %>
<br>
<br>
<label><b>Age: </b></label>
<%= f.number_field :age %>
<br>
<br>
<label><b>Grade: </b></label>
<%= f.number_field :grade %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<h1>Student Index</h1>
<hr>
<p><%= link_to "Add New Student", new_student_path %></p>
<h3><b><u>Students</u></b></h3>
<ul>
    <% @students.each do |student| %>
    <li><p><%= link_to student.name, student_path(student) %></p></li>
    <% end %>
</ul>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>
<hr>
<p><b>Age: </b> <%= @student.age %></p>
<p><b>Grade: </b> <%= @student.grade %></p>
<b>Books: </b> |  <u><%= link_to "Add Book", new_library_path %></u><br>
<ol>
    <% @student.libraries.each do |library| %>
    <li><p><%= library.book.title %></p>
        <ul>
            <li><%= library.book.author %></li>
        </ul>
    </li>
    <% end %>
</ol>
<br>
<br>
<p><%= button_to "Remove Student", student_path(@student), method: :delete %>
<br>
<br>
<p><b><u><%= link_to "Edit Student", edit_student_path %></u></b></p>
<br>
<p><b><u><%= link_to "Index", students_path %></u></b></p>